### PR TITLE
Bugfix

### LINKED ISSUE #170: Seller agreement prohibited transactions section is misnumbered
Numbering jumps from 39-37-39-43-40, etc.

Should be numbered in numeric order.

https://github.com/balanced/www.balancedpayments.com/blob/master/contents/terms/selleragreement.md

### LINKED ISSUE #177: Marketplace agreement reference is incorrect
Section 19, 'Excessive chargebacks', ends with the sentence "Additionally, Balanced may establish conditions similar to those outlined in Section 14. “Fraud or Excessive Chargebacks” on Marketplace."

Section 14 is not 'Fraud or Excessive Chargebacks,' and doesn't outline any conditions.

### PR DESCRIPTION
**Pull request by kyungmin**
- Fixes #177
- Fixes #170

### CODE REVIEW

**Comment by kyungmin** [comment]
@mjallday can you merge this in too?

**Comment by mjallday** [comment]
@kyungmin i strongly feel that we should use automatic numbering as opposed to manual numbering. if we solve this issue correctly then problems like #170 go away. the marketplace agreement is done correctly, what is causing issues on this page that are not on the other?

**Comment by kyungmin** [comment]
@mjallday As far as I know, `1., 2., 3., ...` is the correct syntax to create an ordered list in markdown. What do you mean by automatic numbering?

**Comment by mjallday** [comment]
Sorry, I did not notice you'd move the value in front of the heading. I read it as `### 1. Foo` instead of `1. ### Foo`

**Pull request merged**
